#! /bin/sh
# postrm script for linuxmuster-client-truecrypt
#
# see: dh_installdeb(1)

set -e

# source debconf stuff
#. /usr/share/debconf/confmodule
# sozrce dbconfig-common stuff
#. /usr/share/dbconfig-common/dpkg/postrm.pgsql
# do it
# parameter 1: package name
# parameter 2: arguments that were passed to the maintainer script

# use truecrypt uninstaller to remove truecrypt
if [ -f /usr/bin/truecrypt-uninstall.sh ]; then
  /usr/bin/truecrypt-uninstall.sh
else
  echo "postrm: truecrypt seems to be installed already"
fi


#DEBHELPER#
